# railway.toml
[build]
builder = "NIXPACKS"

[env]
NODE_ENV = "production"
REQUEST_TIMEOUT_MS = "30000"
CONNECTION_TIMEOUT_MS = "60000"
SHUTDOWN_GRACE_MS = "15000"
METRICS_ENABLED = "true"

[service.api]
root = "packages/api"
start = "pnpm start"
# preStart runs from the root directory (packages/api), so use relative path
preStart = "pnpm prisma migrate deploy --schema=./prisma/schema.prisma"

[service.api.healthcheck]
path = "/health/ready"
interval = 10000
timeout  = 10000
