# railway.toml
[build]
builder = "NIXPACKS"

[env]
NODE_ENV = "production"
REQUEST_TIMEOUT_MS = "30000"
CONNECTION_TIMEOUT_MS = "60000"
SHUTDOWN_GRACE_MS = "15000"
METRICS_ENABLED = "true"
NIXPACKS_NODE_VERSION = "20"
NIXPACKS_PNPM_VERSION = "8.15.4"

[service.api]
root = "packages/api"
start = "pnpm start"
# Use @codex/db as the schema owner for migrations
preStart = "pnpm --filter @codex/db exec prisma migrate deploy"

[service.api.healthcheck]
path = "/health/ready"
interval = 10000
timeout  = 10000
