# railway.toml
[build]
builder = "NIXPACKS"

[env]
NODE_ENV = "production"
REQUEST_TIMEOUT_MS = "30000"
CONNECTION_TIMEOUT_MS = "60000"
SHUTDOWN_GRACE_MS = "15000"
METRICS_ENABLED = "true"

[service.api]
root = "packages/api"
start = "pnpm start"
# Prisma will use the "prisma.schema" config from package.json
preStart = "pnpm prisma migrate deploy"

[service.api.healthcheck]
path = "/health/ready"
interval = 10000
timeout  = 10000
