name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "needs-discussion"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us evaluate and implement your idea.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What is the current limitation?
      placeholder: Describe the problem or limitation...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - API (packages/api)
        - Admin Dashboard (apps/admin)
        - Mobile SDK (apps/sdk)
        - Database (packages/db)
        - UI Components (packages/ui)
        - Infrastructure
        - Cross-cutting (multiple components)
        - New component
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical
        - Blocking
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: |
        What specific criteria must be met for this feature to be considered complete?
        Use checkboxes for each criterion.
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3

  - type: textarea
    id: impact
    attributes:
      label: Business Impact
      description: How will this feature benefit users or the business?

  - type: textarea
    id: technical
    attributes:
      label: Technical Considerations
      description: Any technical constraints, dependencies, or implementation notes to consider?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request here.