name: Task/Chore
description: Development task, maintenance, or chore
title: "[TASK] "
labels: ["task"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Use this template for development tasks, maintenance work, or chores that don't fit into bug reports or feature requests.

  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: Clear description of what needs to be done.
      placeholder: Describe the task...
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Task Type
      description: What type of task is this?
      options:
        - Refactoring
        - Documentation
        - Testing
        - Maintenance
        - Performance
        - Security
        - Dependency Update
        - Configuration
        - CI/CD
        - Other
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component does this task affect?
      options:
        - API (packages/api)
        - Admin Dashboard (apps/admin)
        - Mobile SDK (apps/sdk)
        - Database (packages/db)
        - UI Components (packages/ui)
        - Infrastructure
        - Repository (root level)
        - Multiple components
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: |
        What specific criteria must be met for this task to be considered complete?
        Use checkboxes for each criterion.
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this task?
      options:
        - Low
        - Medium
        - High
        - Urgent

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any additional context, links, or references for this task.